### ISSUE TITLE
Can't load a game with an illegal move at the end of the game

### ISSUE THREAD

**Issue by AlexGTrick** [mogproject/mog-frontend#116]
Hello, Yosuke Mizutani!

Rules of shogi state that illegal moves are possible - they mean immediate loss of the player who made an illegal move. So if such a move is played in a game, it is recorded in a kifu.
For example, here is a game: https://system.81dojo.com/en/kifus/5711137

![изображение](https://user-images.githubusercontent.com/35655298/120106945-ae993300-c167-11eb-8373-0b455f65624a.png)

If I try to load the kifu of your site https://play.mogproject.com/, I get an error: 

![изображение](https://user-images.githubusercontent.com/35655298/120107032-05067180-c168-11eb-8966-7eaf43ee6ab5.png)

If we check corresponding line from the .kif file, it is:
```
83   １七玉(28)   (0:6/0:16:37)
*反則手にて終局
```

I believe that it is possible to handle such cases correctly, according to actual shogi rules

**Comment by mogproject** [comment]
Actually, Shogi Playground supports such illegal moves. But it seems that there is a different bug in the KIF-reading process.

If you remove the last line of the file, you'll see something like this: https://play.mogproject.com/?u=~0.7ku2jm7ga2xa83s20s9lo0io8cm1im8821a49cm1e29q80e48uc0nc9uu31u8ps0wu7pe0rw77642a6ba32a7j505m7g857r8gq1ut7cq8ma6ti9qw5oiboa66sc0abo02ai4jibx2bwi0103ej3j0bli2bobei2k28go63t56a0oaboo1em4wn1a4bfo9zy774bzsb96bro29j2o67wj3t65xobjo4x62joblobg6bgobb82a2a3g.i830&bn=Nazar_J&wn=Oragorn&move=84

I will take a look at the code. Thanks for reporting!
